import "./globals.css";
import Fourofour from './not-found'
import {Suspense} from 'react'

export const metadata = {
  title: "klob0t",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Suspense fallback={<Fourofour />}><body>
      {children}
      </body></Suspense>
    </html>
  );
}
